# Generated by Django 4.2.2 on 2023-07-07 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='wholesaler',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mlsapp.wsinfo'),
        ),
    ]
