# Generated by Django 4.2.2 on 2023-06-17 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=1)),
                ('post_crd', models.FloatField(default=0)),
                ('salesfees', models.FloatField(default=0)),
                ('postage', models.FloatField(default=0)),
                ('wac', models.FloatField(default=1)),
                ('profit', models.FloatField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlsapp.static')),
            ],
        ),
    ]
