# Generated by Django 4.2.2 on 2023-06-30 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jf', models.JSONField(default=dict)),
                ('date', models.DateTimeField(default='2001-01-01')),
                ('is_live', models.BooleanField(default=True)),
                ('category', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=500)),
                ('book', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mlsapp.static')),
                ('wholesaler', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mlsapp.wsinfo')),
            ],
            options={
                'unique_together': {('book', 'wholesaler')},
            },
        ),
    ]
