# Generated by Django 4.2.2 on 2023-06-17 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlsapp', '0002_salesdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=13)),
                ('status', models.CharField(default='Active', max_length=13)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlsapp.static')),
            ],
        ),
    ]
