# Generated by Django 4.2.2 on 2023-06-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlsapp', '0002_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='category',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='description',
        ),
        migrations.AddField(
            model_name='static',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='static',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
