# Generated by Django 4.2.2 on 2023-06-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlsapp', '0003_skumap'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvReader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ws_name', models.CharField(max_length=25)),
                ('invispdf', models.BooleanField(default=1)),
                ('params1', models.JSONField()),
                ('params2', models.JSONField()),
                ('params3', models.JSONField()),
                ('regex_num', models.CharField(max_length=50)),
                ('regex_date', models.CharField(max_length=50)),
            ],
        ),
    ]
