# Generated by Django 4.2.2 on 2023-07-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlsapp', '0003_alter_invoicedata_wholesaler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wsinfo',
            name='ccy',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='wsinfo',
            name='csv_disc',
            field=models.FloatField(default=0.5, null=True),
        ),
        migrations.AlterField(
            model_name='wsinfo',
            name='inv_disc',
            field=models.FloatField(default=0.5, null=True),
        ),
        migrations.AlterField(
            model_name='wsinfo',
            name='part_comb',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='wsinfo',
            name='tab_num',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='wsinfo',
            name='terms',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wsinfo',
            name='url',
            field=models.URLField(default=None, null=True),
        ),
    ]
