# Generated by Django 4.2.2 on 2023-07-04 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlsapp', '0003_remove_offers_category_remove_offers_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keepadatafxd',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='offers',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='static',
            name='pubdate',
            field=models.DateField(default=datetime.datetime(2001, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
