# Generated by Django 4.2.2 on 2023-06-20 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlsapp', '0004_invreader'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeepaMAVG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('new', models.FloatField(default=0)),
                ('newfba', models.FloatField(default=0)),
                ('newfbm', models.FloatField(default=0)),
                ('salesrank', models.IntegerField(default=0)),
                ('offerct', models.IntegerField(default=0)),
                ('AZBBpct30', models.FloatField(default=0)),
                ('AZBBpct90', models.FloatField(default=0)),
                ('AZpx', models.FloatField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlsapp.static')),
            ],
        ),
        migrations.CreateModel(
            name='KeepaJSONoffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jf', models.JSONField()),
                ('date', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlsapp.static')),
            ],
        ),
    ]
