# Generated by Django 4.2.2 on 2023-06-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlsapp', '0005_keepamavg_keepajsonoffers'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeepaDataFXD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.JSONField(default='', max_length=20)),
                ('pubdate', models.DateTimeField(default='2001-01-01')),
                ('pap', models.JSONField(default='')),
                ('h', models.IntegerField(default=0)),
                ('l', models.IntegerField(default=0)),
                ('w', models.IntegerField(default=0)),
                ('wt', models.IntegerField(default=0)),
                ('fmt', models.CharField(default='', max_length=20)),
                ('book', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mlsapp.static')),
            ],
        ),
    ]
