# Generated by Django 4.2.2 on 2023-06-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlsapp', '0006_keepadatafxd'),
    ]

    operations = [
        migrations.CreateModel(
            name='WSInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wholesaler', models.CharField(max_length=100)),
                ('params1', models.JSONField()),
                ('style', models.CharField(max_length=100)),
                ('tab_num', models.IntegerField()),
                ('discount', models.FloatField()),
                ('ccy', models.CharField(max_length=10)),
                ('terms', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
    ]
