# Generated by Django 4.2.2 on 2023-06-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlsapp', '0007_wsinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsinfo',
            name='renames',
            field=models.JSONField(default=''),
        ),
        migrations.AlterField(
            model_name='wsinfo',
            name='discount',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='wsinfo',
            name='params1',
            field=models.JSONField(default=''),
        ),
    ]
