# Generated by Django 4.2.2 on 2023-06-28 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlsapp', '0008_wsinfo_renames_alter_wsinfo_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='KeepaJSON8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jf', models.JSONField()),
                ('date', models.DateTimeField()),
                ('is_live', models.BooleanField(default=True)),
                ('book', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mlsapp.static')),
                ('wholesaler', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mlsapp.wsinfo')),
            ],
            options={
                'unique_together': {('book', 'wholesaler')},
            },
        ),
    ]
