# Generated by Django 4.2.2 on 2023-06-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlsapp', '0009_offers_keepajson8'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsinfo',
            name='part_comb',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wsinfo',
            name='url',
            field=models.URLField(default=None),
        ),
    ]
