# Generated by Django 4.2.2 on 2023-06-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlsapp', '0010_wsinfo_part_comb_alter_wsinfo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keepadatafxd',
            name='cat',
            field=models.JSONField(max_length=20),
        ),
    ]
