# Generated by Django 4.2.2 on 2023-06-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlsapp', '0011_alter_keepadatafxd_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keepadatafxd',
            name='cat',
            field=models.JSONField(default={}, max_length=20),
        ),
        migrations.AlterField(
            model_name='keepadatafxd',
            name='pap',
            field=models.JSONField(),
        ),
    ]
