# Generated by Django 4.2.2 on 2023-06-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlsapp', '0012_alter_keepadatafxd_cat_alter_keepadatafxd_pap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keepadatafxd',
            name='pap',
            field=models.JSONField(default={}),
        ),
    ]
