# Generated by Django 4.2.2 on 2023-06-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlsapp', '0014_alter_keepadatafxd_cat_alter_keepadatafxd_pap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wsinfo',
            name='params1',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='wsinfo',
            name='renames',
            field=models.JSONField(default=dict),
        ),
    ]
