# Generated by Django 4.2.2 on 2023-06-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlsapp', '0015_alter_wsinfo_params1_alter_wsinfo_renames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wsinfo',
            old_name='discount',
            new_name='csv_disc',
        ),
        migrations.AddField(
            model_name='wsinfo',
            name='inv_disc',
            field=models.FloatField(default=0.5),
        ),
    ]
