# Generated by Django 4.2.2 on 2023-06-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlsapp', '0016_rename_discount_wsinfo_csv_disc_wsinfo_inv_disc'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsinfo',
            name='csv_cols',
            field=models.JSONField(default=dict),
        ),
    ]
