# Generated by Django 4.2.2 on 2023-06-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlsapp', '0017_wsinfo_csv_cols'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wsinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='wsinfo',
            name='wholesaler',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
