# Generated by Django 4.2.2 on 2023-06-30 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlsapp', '0018_remove_wsinfo_id_alter_wsinfo_wholesaler'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='book',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mlsapp.static'),
        ),
        migrations.AddField(
            model_name='offers',
            name='date',
            field=models.DateTimeField(default='2001-01-01'),
        ),
        migrations.AddField(
            model_name='offers',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='jf',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='offers',
            name='wholesaler',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mlsapp.wsinfo'),
        ),
        migrations.AlterUniqueTogether(
            name='offers',
            unique_together={('book', 'wholesaler')},
        ),
        migrations.DeleteModel(
            name='KeepaJSON8',
        ),
    ]
